### PR TITLE
Fix exclude handling

### LINKED ISSUE #40: not Updating packages on node 6
Hi, thanks for this tool.
I had problems using updtr on node 6 (node 4 is fine) 

Found that `isExcluded()` in `filter.js` returns null on node 6.
So i made a little fix for myself in isExcluded function:

changed line 23 to:
`return !!info.name.match(new RegExp("^(" + excludedModules.join("|") + ")$"));`

### PR DESCRIPTION
**Pull request by simono**
18f7a8dd968 introduced a broken `isExcluded()`. `match()` returns an
array with matches or null if none was found. So `isExcluded` never
returned false.

We now use `indexOf()` instead of constructing a RegExp.

This fixes #40.

### CODE REVIEW

**Comment by matthaias** [comment]
Looks good, thanks! @jhnns can you please take a look?

File: test/run.js [hunk 1]
```diff
@@ -289,7 +289,7 @@ var expectedOptionsWithCurrentCountWantedAndSpecifiedRegistry = {
         updateTo: "1.1.5"
     },
     testCmd: "npm test",
-    installCmd: "npm i --registry https://curstom.npm.registry"
```
Comment (matthaias) [inline test/run.js]: Thanks for spotting this :)

File: lib/filter.js [hunk 2]
```diff
@@ -16,11 +16,9 @@ function isUnstable(info) {
 }
 
 function isExcluded(info, exclude) {
-    var excludedModules = exclude.map(function (name) {
+    return exclude.map(function (name) {
         return name.trim();
-    });
-
-    return info.name.match(new RegExp("^(" + excludedModules.join("|") + ")$"));
+    }).indexOf(info.name) !== -1;
```
Comment (jhnns) [inline lib/filter.js]: Nice one 👍 
This implementation is so much simpler, didn't see this.

**Comment by jhnns** [comment]
Awesome! 👍 

Our tests had a flaw where tests were not failing although big parts of the application were not executed. We should have noted the sudden decrease of test coverage though.

**Comment by simono** [comment]
Great, thanks for merging :)

**Comment by jhnns** [comment]
Shipped with `0.2.1`
